# Mandatory configs
input: 
  - "img"
  - "bboxes"
  - "bbox_labels"
output: 
  - "obj_tags"
  - "bboxes"
  - "bbox_labels"
  - "bus_tracks"
  - "person_tracks"
  - "bus_ids"
  - "person_ids"
  - "rescale_function"

# Optional configs depending on node
sort_person_tracker:
  DEFAULT_MAX_AGE: 5                  # How many frames should a tracker stay without update and without successfully getting tracking state
  DEFAULT_MIN_HITS: 4                 # Minimum hits to create a new tracker object
  DEFAULT_USE_TIME_SINCE_UPDATE: 200  # How many frames should a tracker stay without update even with successful tracking state
  DEFAULT_IOU_THRESHOLD: 0.5          # IOU threshold for matching the detection and the prediction from the tracker
  TRACKER_TYPE: 'medianflow'

sort_bus_tracker:
  DEFAULT_MAX_AGE: 100
  DEFAULT_MIN_HITS: 1
  DEFAULT_USE_TIME_SINCE_UPDATE: 200
  DEFAULT_IOU_THRESHOLD: 0.5
  TRACKER_TYPE: 'medianflow'

multithread: True                     # Multithreading for tracking. One thread for bus the other for person
show_class_in_tag: False              # Whether to show the class name in the bbox
detection:            
  draw_bbox: True                     # Whether to draw detection bboxes
  include_tag: True                   # Whether to include tag to indicate the bbox is for detection
