# A list of tuples with 1st element being the callable for which image drawing operation would be performed 
# and the second element is the dictionary of keyword arguments for the callable
input: ["draw_pipeline"]   
output: ["none"]
