nodes:
- input.live:
    input_source: 1
    threading: True

- model.yolo:
    model_type: "v4"            # {"v4, "v4tiny"}
    num_classes: 1
    detect_ids: [0]
    yolo_iou_threshold: 0.5
    yolo_score_threshold: 0.2

- model.hrnet:
    score_threshold: 0.1

- custom_nodes.dabble.dab_recognition
# - draw.legend:
#     all_legend_items: ["fps"]   # ["fps", "count", "zone_count"]
#     position: "top"          # {"top", "bottom"}
#     include: ["all_legend_items"]
- draw.bbox
- draw.tag
- draw.poses
- output.screen
